coverage:
  precision: 2
  round: down
  range: "60..100"

  status:
    project:
      default:
        threshold: 1 # decrease by up to 1% doesn't result in failure
        paths:
          - "src"
          - "include"
        branches:
          - main

    # check only the diff of the PR
    patch:
      default:
        threshold: 1
        paths:
          - "src"
          - "include"
        branches:
          - main
        only_pulls: true
