ignore:
  - "xmpsdk"  # Not interested about the coverage of XMKSDK

coverage:
  status:
    project:
      default:
        target: 70%    # the required coverage value
        threshold: 1%  # the leniency in hitting the target
