ssh rmills@rmillsmm                                             '~/gnu/exiv2/buildserver/contrib/buildserver/dailyTest.sh'
ssh rmills@rmillsmm-kubuntu                                     '~/gnu/exiv2/buildserver/contrib/buildserver/dailyTest.sh'
ssh rmills@rmillsmm-w7                                          '~/gnu/exiv2/buildserver/contrib/buildserver/dailyTest.sh'
ssh rmills@rmillsmm-w7 'export PLATFORM=msvc                    ;~/gnu/exiv2/buildserver/contrib/buildserver/dailyTest.sh'
ssh rmills@rmillsmm-w7 'export PLATFORM=mingw; export win32=true;~/contrib/buildserver/dailyCMake.sh'
