ce addmoddel\addmoddel.vcproj
ce convert-test\convert-test.vcproj
ce exifcomment\exifcomment.vcproj
ce exifdata-test\exifdata-test.vcproj
ce exifprint\exifprint.vcproj
ce exiv2\exiv2.vcproj
ce exiv2lib\exiv2lib.vcproj
ce exivsimple\exivsimple.vcproj
ce expat\expat.vcproj
ce iotest\iotest.vcproj
ce iptceasy\iptceasy.vcproj
ce iptcprint\iptcprint.vcproj
ce iptctest\iptctest.vcproj
ce largeiptc-test\largeiptc-test.vcproj
ce metacopy\metacopy.vcproj
ce mmap-test\mmap-test.vcproj
ce prevtest\prevtest.vcproj
ce stringto-test\stringto-test.vcproj
ce taglist\taglist.vcproj
ce tiff-test\tiff-test.vcproj
ce utiltest\utiltest.vcproj
ce write-test\write-test.vcproj
ce write2-test\write2-test.vcproj
ce xmpparse\xmpparse.vcproj
ce xmpparser-test\xmpparser-test.vcproj
ce xmpsample\xmpsample.vcproj
ce xmpsdk\xmpsdk.vcproj
ce zlib\zlib.vcproj
ce exiv2.sln
ce expat\expat.sln
ce zlib\zlib.sln
