Vagrant.configure("2") do |config|

  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.define "Fedora" do |fedora|
    fedora.vm.box = "fedora/29-cloud-base"
    fedora.vm.hostname = "fedora-exiv2"
  end

  config.vm.define "Debian" do |debian|
    debian.vm.box = "generic/debian9"
    debian.vm.hostname = "debian-exiv2"
  end

  config.vm.define "Archlinux" do |archlinux|
    archlinux.vm.box = "archlinux/archlinux"
    archlinux.vm.hostname = "archlinux-exiv2"
  end

  config.vm.define "Ubuntu" do |ubuntu|
    ubuntu.vm.box = "generic/ubuntu1810"
    ubuntu.vm.hostname = "ubuntu-exiv2"
  end

  config.vm.define "CentOS" do |centos|
    centos.vm.box = "centos/7"
    centos.vm.hostname = "centos-exiv2"
  end

  config.vm.define "OpenSUSE" do |opensuse|
    opensuse.vm.box = "opensuse/openSUSE-Tumbleweed-x86_64"
    opensuse.vm.hostname = "opensuse-exiv2"
  end

  config.vm.define "Alpine" do |alpine|
    alpine.vm.box = "roboxes/alpine39"
    # don't set a custom hostname, this is broken on Alpine
    # alpine.vm.hostname = "alpine-exiv2"
  end

  # use the CI script from gitlab to setup all dependencies
  config.vm.provision "install_dependencies", type: "shell" do |shell|
    shell.path = "../../ci/install_dependencies.sh"
  end

  # install additional dependencies for development
  config.vm.provision "install_devel_dependencies", type: "shell" do |shell|
    shell.path = "setup.sh"
  end

  # install conan & clone the exiv2 repo
  config.vm.provision "setup_repository", type: "shell" do |shell|
    shell.path = "setup_user.sh"
    shell.privileged = false
  end

end
