// File generated by cmake from cmake/config.h.cmake.

#ifndef _EXV_CONF_H_
#define _EXV_CONF_H_

// Define to 1 if you want to use libcurl in httpIO.
#cmakedefine EXV_USE_CURL

// Define to 1 if you want to enable filesystem access
#cmakedefine EXV_ENABLE_FILESYSTEM

// Define if you require webready support.
#cmakedefine EXV_ENABLE_WEBREADY

// Define if you want translation of program messages to the user's native language
#cmakedefine EXV_ENABLE_NLS

// Define if you want to enable the decoding of video metadata
#cmakedefine EXV_ENABLE_VIDEO

// Define if you want BMFF support.
#cmakedefine EXV_ENABLE_BMFF

// Define if you want to use the inih library.
#cmakedefine EXV_ENABLE_INIH

// Define if you have the std::format function.
#cmakedefine EXV_HAVE_STD_FORMAT

// Define if you have the strerror_r function.
#cmakedefine EXV_HAVE_STRERROR_R

// Define if the strerror_r function returns char*.
#cmakedefine EXV_STRERROR_R_CHAR_P

/* Define to `const' or to empty, depending on the second argument of `iconv'. */
#cmakedefine ICONV_ACCEPTS_CONST_INPUT

#if defined(__NetBSD__)
#include <sys/param.h>
#if __NetBSD_Prereq__(9,99,17)
#define NETBSD_POSIX_ICONV 1
#else
#define NETBSD_POSIX_ICONV 0
#endif
#endif

#if defined(ICONV_ACCEPTS_CONST_INPUT) || (defined(__NetBSD__) && !NETBSD_POSIX_ICONV)
#define EXV_ICONV_CONST const
#else
#define EXV_ICONV_CONST
#endif

// Define if you have the zlib library.
#cmakedefine EXV_HAVE_LIBZ

// Define if you have the brotli library.
#cmakedefine EXV_HAVE_BROTLI

/* Define if you have (Exiv2/xmpsdk) Adobe XMP Toolkit. */
#cmakedefine EXV_HAVE_XMP_TOOLKIT

/* Define to the full name of this package. */
#cmakedefine EXV_PACKAGE_NAME "@EXV_PACKAGE_NAME@"

/* Define to the full name and version of this package. */
#cmakedefine EXV_PACKAGE_STRING "@EXV_PACKAGE_STRING@"

/* Define to the version of this package. */
#cmakedefine EXV_PACKAGE_VERSION "@PROJECT_VERSION@"

#define EXIV2_MAJOR_VERSION (@PROJECT_VERSION_MAJOR@U)
#define EXIV2_MINOR_VERSION (@PROJECT_VERSION_MINOR@U)
#define EXIV2_PATCH_VERSION (@PROJECT_VERSION_PATCH@U)
#define EXIV2_TWEAK_VERSION (@PROJECT_VERSION_TWEAK@U)

// Definition to enable translation of Nikon lens names.
#cmakedefine EXV_HAVE_LENSDATA

// Define if you have the iconv function.
#cmakedefine EXV_HAVE_ICONV

#endif /* !_EXV_CONF_H_ */
