name: On PRs - Linux Special Builds

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - "*.md"

permissions:
  contents: read

jobs:
  special_debugRelease:
    name: 'Ubuntu - GCC - Debug+Coverage'
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 2
          persist-credentials: false
          # Trying to deal with warning: ->  Issue detecting commit SHA. Please run actions/checkout with fetch-depth > 1 or set to 0

      - name: Install dependencies
        run: |
          sudo eatmydata apt-get update
          sudo eatmydata apt-get -y install libbrotli-dev libcurl4-openssl-dev libinih-dev libgmock-dev python3-lxml gcovr

      - name: Build
        run: |
          cmake --preset linux-coverage -S . -B build
          cmake --build build --parallel

      - name: Tests + Upload coverage
        run: |
          ctest --test-dir build --output-on-failure
          # this needs to match the ecommand in on_push_ExtraJobsForMain.yml!
          gcovr --root . --object-dir build --exclude-unreachable-branches --exclude-throw-branches --xml -o build/coverage.xml build
          curl https://keybase.io/codecovsecops/pgp_keys.asc | gpg --import
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          curl -Os https://uploader.codecov.io/latest/linux/codecov.SHA256SUM
          curl -Os https://uploader.codecov.io/latest/linux/codecov.SHA256SUM.sig
          gpg --verify codecov.SHA256SUM.sig codecov.SHA256SUM
          shasum -a 256 -c codecov.SHA256SUM
          chmod +x codecov
          ./codecov -f build/coverage.xml

  special_releaseValgrind:
    name: 'Ubuntu - GCC - Release+Valgrind'
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Install dependencies
        run: |
          sudo eatmydata apt-get update
          sudo eatmydata apt-get -y install libbrotli-dev libcurl4-openssl-dev libinih-dev libgmock-dev python3-lxml valgrind

      - name: Build
        run: |
          cmake --preset linux-release -S . -B build
          cmake --build build --parallel

      - name: Tests with Valgrind
        run: |
          cd build/bin
          valgrind ./unit_tests


  special_releaseSanitizers:
    name: 'Ubuntu - GCC - Release+Sanitizers'
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Install dependencies
        run: |
          sudo eatmydata apt-get update
          sudo eatmydata apt-get -y install libbrotli-dev libcurl4-openssl-dev libinih-dev libgmock-dev python3-lxml

      - name: Build
        run: |
          cmake --preset linux-sanitizers -S . -B build
          cmake --build build --parallel

      - name: Tests
        run: |
          ctest --test-dir build --output-on-failure

  special_noFilesystemAccess:
    name: 'Ubuntu - GCC - No filesystem access build'
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Install dependencies
        run: |
          sudo eatmydata apt-get update
          sudo eatmydata apt-get -y install libbrotli-dev libcurl4-openssl-dev libinih-dev libgmock-dev python3-lxml

      - name: Build
        run: |
          cmake --preset linux-release -S . -B build -DEXIV2_ENABLE_FILESYSTEM_ACCESS=OFF -DEXIV2_BUILD_SAMPLES=OFF -DEXIV2_BUILD_UNIT_TESTS=OFF -DEXIV2_BUILD_EXIV2_COMMAND=OFF
          cmake --build build --parallel

  special_allEnabled:
    name: 'Ubuntu - GCC - All Options Enabled + Documentation'
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Install dependencies
        run: |
          sudo eatmydata apt-get update
          sudo eatmydata apt-get -y install doxygen graphviz gettext libbrotli-dev libcurl4-openssl-dev libinih-dev libgmock-dev python3-lxml

      - name: Build
        env:
          CXXFLAGS: -DEXIV2_DEBUG_MESSAGES
        run: |
          cmake --preset linux-release -S . -B build -DEXIV2_BUILD_DOC=ON
          cmake --build build --parallel

      - name: Generate documentation
        run: |
          cmake --build build -t doc

  special_conan:
    name: 'Ubuntu - GCC - Conan build'
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Install dependencies
        run: |
          sudo eatmydata apt-get update
          sudo eatmydata apt-get -y install python3-lxml

      - name: Conan common config
        run: |
          python3 -m pip install conan
          conan profile detect --name default --force

      - name: Run Conan
        run: |
          mkdir build
          conan install . -o '&:webready=True' --build missing --output-folder=build

      - name: Build
        run: |
          cmake --preset linux-release -S . -B build
          cmake --build build --parallel

      - name: Tests
        run: |
          ctest --test-dir build --output-on-failure
