name: Linux Special Builds on PRs

on: [pull_request]

jobs:
  special_debugRelease:
    name: 'Ubuntu 20.04 - GCC - Debug+Coverage'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
          # Trying to deal with warning: ->  Issue detecting commit SHA. Please run actions/checkout with fetch-depth > 1 or set to 0

      - name: install dependencies
        run: |
          sudo apt-get install ninja-build
          pip3 install conan==1.36.0

      - name: Conan common config
        run: |
          conan profile new --detect default
          conan profile update settings.compiler.libcxx=libstdc++11 default

      - name: Run Conan
        run: |
          mkdir build && cd build
          conan profile list
          conan profile show default
          conan install .. -o webready=True --build missing

      - name: Build
        run: |
          cd build
          cmake -GNinja -DCMAKE_BUILD_TYPE=Debug -DBUILD_SHARED_LIBS=ON -DEXIV2_ENABLE_PNG=ON -DEXIV2_ENABLE_WEBREADY=ON -DEXIV2_ENABLE_CURL=ON -DEXIV2_BUILD_UNIT_TESTS=ON -DEXIV2_ENABLE_BMFF=ON -DEXIV2_TEAM_WARNINGS_AS_ERRORS=ON -DBUILD_WITH_COVERAGE=ON -DCMAKE_INSTALL_PREFIX=install ..
          cmake --build .

      - name: Tests + Upload coverage
        env:
          EXIV2_EXT: .exe
        run: |
          cd build
          ctest --output-on-failure
          bash <(curl -s https://codecov.io/bash)

  special_releaseValgrind:
    name: 'Ubuntu 20.04 - GCC - Release+Valgrind'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install valgrind ninja-build
          pip3 install conan==1.36.0

      - name: Conan common config
        run: |
          conan profile new --detect default
          conan profile update settings.compiler.libcxx=libstdc++11 default

      - name: Run Conan
        run: |
          mkdir build && cd build
          conan profile list
          conan profile show default
          conan install .. -o webready=True --build missing

      - name: Build
        run: |
          cd build
          cmake -GNinja -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON -DEXIV2_ENABLE_PNG=ON -DEXIV2_ENABLE_WEBREADY=ON -DEXIV2_ENABLE_CURL=ON -DEXIV2_BUILD_UNIT_TESTS=ON -DEXIV2_ENABLE_BMFF=ON -DEXIV2_TEAM_WARNINGS_AS_ERRORS=ON -DBUILD_WITH_COVERAGE=OFF -DCMAKE_INSTALL_PREFIX=install ..
          cmake --build .

      - name: Tests with valgrind
        env:
          EXIV2_EXT: .exe
        run: |
          cd build/bin
          valgrind ./unit_tests


  special_releaseSanitizers:
    name: 'Ubuntu 20.04 - GCC - Release+Sanitizers'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: install dependencies
        run: |
          sudo apt-get install ninja-build
          pip3 install conan==1.36.0

      - name: Conan common config
        run: |
          conan profile new --detect default
          conan profile update settings.compiler.libcxx=libstdc++11 default

      - name: Run Conan
        run: |
          mkdir build && cd build
          conan profile list
          conan profile show default
          conan install .. -o webready=True --build missing

      - name: Build
        run: |
          cd build
          cmake -GNinja -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON -DEXIV2_ENABLE_PNG=ON -DEXIV2_ENABLE_WEBREADY=ON -DEXIV2_ENABLE_CURL=ON -DEXIV2_BUILD_UNIT_TESTS=ON -DEXIV2_ENABLE_BMFF=ON -DEXIV2_TEAM_WARNINGS_AS_ERRORS=ON -DBUILD_WITH_COVERAGE=OFF -DEXIV2_TEAM_USE_SANITIZERS=ON -DCMAKE_INSTALL_PREFIX=install ..
          cmake --build .

      - name: Tests
        env:
          EXIV2_EXT: .exe
        run: |
          cd build
          ctest --output-on-failure

  special_allEnabled:
    name: 'Ubuntu 20.04 - GCC - All Options Enabled'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install valgrind doxygen graphviz gettext
          pip3 install conan==1.36.0

      - name: Conan common config
        run: |
          conan profile new --detect default
          conan profile update settings.compiler.libcxx=libstdc++11 default

      - name: Run Conan
        run: |
          mkdir build && cd build
          conan profile list
          conan profile show default
          conan install .. -o webready=True --build missing

      - name: Build
        run: |
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON -DEXIV2_ENABLE_PNG=ON -DEXIV2_ENABLE_WEBREADY=ON -DEXIV2_ENABLE_CURL=ON -DEXIV2_BUILD_UNIT_TESTS=ON -DEXIV2_ENABLE_BMFF=ON -DEXIV2_TEAM_WARNINGS_AS_ERRORS=ON -DBUILD_WITH_COVERAGE=ON -DEXIV2_BUILD_DOC=ON -DEXIV2_ENABLE_NLS=ON -DCMAKE_CXX_FLAGS="-DEXIV2_DEBUG_MESSAGES" ..
          make -j

      - name: Generate documentation
        run: |
          make doc

  special_FedoraMinGW:
    name: 'Fedora MinGW'
    runs-on: ubuntu-latest
    container:
        image: "fedora:latest"

    steps:
      - uses: actions/checkout@v2

      - name: install dependencies
        run: |
            dnf -y upgrade
            dnf -y install mingw64-gcc-c++ mingw64-filesystem mingw64-expat mingw64-zlib cmake make

      - name: Build
        run:
            python3 ci/test_build.py --without-tests --cmake-executable "mingw64-cmake" --cmake-options "-DEXIV2_TEAM_EXTRA_WARNINGS=OFF -DEXIV2_TEAM_WARNINGS_AS_ERRORS=OFF -DEXIV2_ENABLE_WEBREADY=ON -DEXIV2_ENABLE_WIN_UNICODE=ON " --compilers --shared-libs OFF
