name: Linux Special Builds on PRs

on: [pull_request]

jobs:
  special_debugRelease:
    name: 'Ubuntu 20.04 - GCC - Debug+Coverage'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
          # Trying to deal with warning: ->  Issue detecting commit SHA. Please run actions/checkout with fetch-depth > 1 or set to 0

      - name: install dependencies
        run: |
          pip3 install conan==1.36.0

      - name: Conan common config
        run: |
          conan profile new --detect default
          conan profile update settings.compiler.libcxx=libstdc++11 default

      - name: Run Conan
        run: |
          mkdir build && cd build
          conan profile list
          conan profile show default
          conan install .. -o webready=True --build missing

      - name: Build
        run: |
          cd build
          cmake -DCMAKE_BUILD_TYPE=Debug -DBUILD_SHARED_LIBS=ON -DEXIV2_ENABLE_PNG=ON -DEXIV2_ENABLE_WEBREADY=ON -DEXIV2_ENABLE_CURL=ON -DEXIV2_BUILD_UNIT_TESTS=ON -DEXIV2_ENABLE_BMFF=ON -DEXIV2_TEAM_WARNINGS_AS_ERRORS=ON -DBUILD_WITH_COVERAGE=ON -DCMAKE_INSTALL_PREFIX=install ..
          make -j

      - name: Tests + Upload coverage
        env:
          EXIV2_EXT: .exe
        run: |
          cd build/bin
          ./unit_tests
          cd ../../tests/
          python runner.py -v
          bash <(curl -s https://codecov.io/bash)

  special_releaseValgrind:
    name: 'Ubuntu 20.04 - GCC - Release+Valgrind'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install valgrind
          pip3 install conan==1.36.0

      - name: Conan common config
        run: |
          conan profile new --detect default
          conan profile update settings.compiler.libcxx=libstdc++11 default

      - name: Run Conan
        run: |
          mkdir build && cd build
          conan profile list
          conan profile show default
          conan install .. -o webready=True --build missing

      - name: Build
        run: |
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON -DEXIV2_ENABLE_PNG=ON -DEXIV2_ENABLE_WEBREADY=ON -DEXIV2_ENABLE_CURL=ON -DEXIV2_BUILD_UNIT_TESTS=ON -DEXIV2_ENABLE_BMFF=ON -DEXIV2_TEAM_WARNINGS_AS_ERRORS=ON -DBUILD_WITH_COVERAGE=OFF -DCMAKE_INSTALL_PREFIX=install ..
          make -j

      - name: Tests with valgrind
        env:
          EXIV2_EXT: .exe
        run: |
          cd build/bin
          valgrind ./unit_tests


  special_releaseSanitizers:
    name: 'Ubuntu 20.04 - GCC - Release+Sanitizers'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: install dependencies
        run: |
          pip3 install conan==1.36.0

      - name: Conan common config
        run: |
          conan profile new --detect default
          conan profile update settings.compiler.libcxx=libstdc++11 default

      - name: Run Conan
        run: |
          mkdir build && cd build
          conan profile list
          conan profile show default
          conan install .. -o webready=True --build missing

      - name: Build
        run: |
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON -DEXIV2_ENABLE_PNG=ON -DEXIV2_ENABLE_WEBREADY=ON -DEXIV2_ENABLE_CURL=ON -DEXIV2_BUILD_UNIT_TESTS=ON -DEXIV2_ENABLE_BMFF=ON -DEXIV2_TEAM_WARNINGS_AS_ERRORS=ON -DBUILD_WITH_COVERAGE=OFF -DEXIV2_TEAM_USE_SANITIZERS=ON -DCMAKE_INSTALL_PREFIX=install ..
          make -j

      - name: Tests
        env:
          EXIV2_EXT: .exe
        run: |
          cd build/bin
          ./unit_tests
          cd ../../tests/
          python runner.py -v
